services:
  - type: web
    name: email-spam-detector
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app_simple.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000